# Generated by Django 6.0.2 on 2026-04-28 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Patika Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('seviye', models.CharField(choices=[('baslangic', 'Başlangıç'), ('orta', 'Orta'), ('ileri', 'İleri')], default='baslangic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patikaları', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patika',
                'verbose_name_plural': 'Patikalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatikaAdim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(default=1)),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('patika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adimlar', to='mentoring.patika')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='MentorTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField(blank=True, verbose_name='Tanışma Mesajı')),
                ('status', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_talepler', to=settings.AUTH_USER_MODEL)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_talepler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Talebi',
                'verbose_name_plural': 'Mentor Talepleri',
                'ordering': ['-created_at'],
                'unique_together': {('ogrenci', 'mentor')},
            },
        ),
    ]
