# Generated by Django 6.0.2 on 2026-04-25 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('level', models.CharField(choices=[('baslangic', 'Başlangıç'), ('orta', 'Orta'), ('ileri', 'İleri')], default='baslangic', max_length=20, verbose_name='Seviye')),
                ('status', models.CharField(choices=[('devam', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('beklemede', 'Beklemede')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eğitim Modülü',
                'verbose_name_plural': 'Eğitim Modülleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
