# Generated by Django 6.0.2 on 2026-04-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(verbose_name='Soru')),
                ('secenek_a', models.CharField(max_length=200, verbose_name='Seçenek A')),
                ('secenek_b', models.CharField(max_length=200, verbose_name='Seçenek B')),
                ('secenek_c', models.CharField(max_length=200, verbose_name='Seçenek C')),
                ('secenek_d', models.CharField(max_length=200, verbose_name='Seçenek D')),
                ('dogru_cevap', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru Cevap')),
                ('kategori', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('genel', 'Genel Programlama'), ('veritabani', 'Veritabanı'), ('web', 'Web Geliştirme')], default='genel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz Sorusu',
                'verbose_name_plural': 'Quiz Soruları',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Skor')),
                ('toplam_soru', models.IntegerField(default=0, verbose_name='Toplam Soru')),
                ('kategori', models.CharField(default='genel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Quiz Sonucu',
                'verbose_name_plural': 'Quiz Sonuçları',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
