# Generated by Django 6.0.2 on 2026-04-28 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_developmentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begeniler', models.ManyToManyField(blank=True, related_name='begenilen_postlar', to=settings.AUTH_USER_MODEL)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_postlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Gönderisi',
                'verbose_name_plural': 'Forum Gönderileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('begeniler', models.ManyToManyField(blank=True, related_name='begenilen_yorumlar', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='education.forumpost')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_yorumlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Yorumu',
                'verbose_name_plural': 'Forum Yorumları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kulup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kulüp Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturulan_kulupler', to=settings.AUTH_USER_MODEL)),
                ('uyeler', models.ManyToManyField(blank=True, related_name='katildigi_kulupler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kulüp',
                'verbose_name_plural': 'Kulüpler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='forumpost',
            name='kulup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlar', to='education.kulup'),
        ),
    ]
